apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: guestbook
    tier: backend
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 80
  selector:
    app: guestbook
    tier: backend